sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gjuoun/travisci-playground:1.0 -f Dockerfile.dev .

script:
  - docker run -e CI=true gjuoun/travisci-playground:1.0 yarn test